### ISSUE TITLE
Feature Request: Toggle for RMS or Peak

### ISSUE THREAD

**Issue by AndrewRahman** [DanielRudrich/OomphSC#5]
Would be nice to have a toggle between Peak and RMS. We're doing some tests now and the RMS value is super low for impulse sounds, but what we need is the peak data so that we can make some spikes in the visuals.

**Comment by DanielRudrich** [comment]
That's actually already implemented, but I haven't found time to add a GUI widget to change it to Peak. If you disable the UI in Reaper, you see the bare parameters, there should be one named level calculation type (or the like). I recommend using higher release times with it. Maybe I should add a *hold time* as well?

**Comment by DanielRudrich** [comment]
This is now on the main branch! Check out the github actions for binaries: https://github.com/DanielRudrich/OomphSC/actions/runs/2012977091

I have to say, it doesn't make a lot difference switching between RMS and Peak, as it basically does the same, RMS will just square the sample values before applying the ballistics (attack and release). What it actually does is expanding the samples (making loud ones louder). 

In order to better catch transients: short attack and longer release times.

**Comment by DanielRudrich** [comment]
removed that feature and replaced it with the stereo/mono-sum modes
